Repository miguel5g/pallas, pull requests merged in 2022-12, with the labels that each got.

#33 Create get all todos resource
  .github/workflows/pull_request.yml
  docker-compose.test.yml
  docker-compose.yml
  jest-e2e.config.js
  jest.config.js
  package.json
  src/controllers/todos/get-all-todos.controller.js
  src/controllers/todos/get-all-todos.controller.spec.js
  src/routes/index.js
  src/routes/todos.routes.js
  src/services/todos/get-all-todos.service.js
  src/services/todos/get-all-todos.service.spec.js
  src/tests/e2e/auth.spec.js
  src/tests/e2e/todo.spec.js
  src/tests/e2e/users.spec.js
  src/tests/helpers/express-mocks.js
  src/tests/helpers/prisma-mock.js
Labels: enhancement

#36 Add create todo endpoint
  src/controllers/todos/create-todo.controller.js
  src/controllers/todos/create-todo.controller.spec.js
  src/routes/todos.routes.js
  src/services/todos/create-todo.service.js
  src/services/todos/create-todo.service.spec.js
  src/tests/e2e/todo.spec.js
  src/validators/create-todo.validator.js
  src/validators/index.js
Labels: enhancement

#43 Add project license
  LICENSE
Labels: documentation

#38 Create status codes to errors types
  src/errors/bad-request.error.js
  src/errors/internal-server.error.js
  src/errors/not-found.error.js
  src/errors/not-implemented.error.js
  src/errors/status-codes.js
  src/errors/too-many-requests.error.js
  src/errors/unauthorized.error.js
Labels: good first issue
